import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { decodeDataFrame, encodeDataFrame, LEGACY_PROTOCOL_VERSION } from "./data-frame.js";
import {
  legacyClientMessageSchema,
  parseClientMessage,
  parseServerMessage,
  roomEventSchema,
  serverMessageSchema,
} from "./messages.js";

// JSON fixtures are shared with the future Java implementation; expected bytes
// are fixed independently of this codec, not generated by encodeDataFrame.
const fixtures = JSON.parse(
  readFileSync(new URL("../fixtures/wire-v7.json", import.meta.url), "utf8"),
) as {
  protocolVersion: number;
  messages: Array<{ name: string; direction: string; raw: string; expected: unknown }>;
  invalidMessages: Array<{ name: string; direction: string; raw: string }>;
  binary: Array<{
    name: string;
    hex: string;
    expected: {
      kind: "input" | "output";
      terminalId: number;
      seq: number;
      leaseId?: number;
      payloadHex: string;
    };
  }>;
  malformedBinary: string[];
};

describe("language-neutral protocol v7 fixtures", () => {
  it("pins the negotiated protocol version", () => {
    expect(LEGACY_PROTOCOL_VERSION).toBe(fixtures.protocolVersion);
  });

  it("covers every message type and room event kind", () => {
    for (const [direction, schema] of [
      ["client", legacyClientMessageSchema],
      ["server", serverMessageSchema],
    ] as const) {
      const covered = new Set(
        fixtures.messages
          .filter((fixture) => fixture.direction === direction)
          .map((fixture) => (fixture.expected as { type: string }).type),
      );
      expect([...covered].sort()).toEqual(
        schema.options.map((option) => option.shape.type.value).sort(),
      );
    }
    const kinds = fixtures.messages.flatMap((fixture) => {
      const message = fixture.expected as { type: string; event?: { kind: string } };
      return message.type === "room-event" ? [message.event!.kind] : [];
    });
    expect([...new Set(kinds)].sort()).toEqual(
      roomEventSchema.options.map((option) => option.shape.kind.value).sort(),
    );
  });

  for (const fixture of fixtures.messages) {
    it(fixture.name, () => {
      const parse = fixture.direction === "client" ? parseClientMessage : parseServerMessage;
      expect(parse(fixture.raw)).toEqual({ kind: "ok", message: fixture.expected });
    });
  }

  for (const fixture of fixtures.invalidMessages) {
    it(fixture.name, () => {
      const parse = fixture.direction === "client" ? parseClientMessage : parseServerMessage;
      expect(parse(fixture.raw).kind).toBe("bad-message");
    });
  }

  for (const fixture of fixtures.binary) {
    it(fixture.name, () => {
      const { payloadHex, leaseId, ...fields } = fixture.expected;
      const payload = Uint8Array.from(Buffer.from(payloadHex, "hex"));
      const expected =
        fields.kind === "input"
          ? { ...fields, kind: "input" as const, leaseId: leaseId!, payload }
          : { ...fields, kind: "output" as const, payload };
      expect(decodeDataFrame(Uint8Array.from(Buffer.from(fixture.hex, "hex")))).toEqual({
        kind: "ok",
        frame: expected,
      });
      expect(Buffer.from(encodeDataFrame(expected)).toString("hex")).toBe(fixture.hex);
    });
  }

  for (const hex of fixtures.malformedBinary) {
    it(`rejects malformed bytes: ${hex || "empty"}`, () => {
      expect(decodeDataFrame(Buffer.from(hex, "hex")).kind).toBe("malformed");
    });
  }
});
